---
elassandra_version: "6.2.3.16"
strapack_version: "6.2.3.16"

elassandra_rpm: "elassandra-{{ elassandra_version }}.rpm"
elassandra_rpm_url: "https://github.com/strapdata/elassandra/releases/download/v{{ elassandra_version }}/elassandra-{{ elassandra_version }}.rpm"
strapack_zip_url: "https://cdn.repo.strapdata.com/enterprise/strapdata-enterprise-{{ strapack_version }}.zip"

# Cassandra configuration
elassandra_cluster_name: TestCluster
elassandra_dc: DC1
elassandra_rack: rack1
elassandra_listen_address: "127.0.0.1"
elassandra_broadcast_rpc_address: "127.0.0.1"

# if you use old version of elassandra that doesn't use CASSANDRA_DAEMON environment variable,
# set elassandra_force_es to "-e" to enable elasticsearch in the systemd script
elassandra_main_class: "org.apache.cassandra.service.ElassandraDaemon"
# For cassandra only nodes:
#elassandra_main_class: "org.apache.cassandra.service.CassandraDaemon"


elassandra_user: cassandra
elassandra_group: cassandra
elassandra_password_jmx: cassandra
elassandra_password_admin: cassandra
elassandra_pid_dir: "/var/run/cassandra"
elassandra_env_file: "/etc/default/cassandra"

elassandra_seed_list: "172.16.1.4"
elassandra_num_token: 32
elassandra_enable_udf: false

cassandra_heapdump_dir: "/tmp"
#elassandra_hints_directory: /var/lib/cassandra/hints
#elassandra_commitlog_directory: /var/lib/cassandra/commitlog
#elassandra_saved_caches_directory: /var/lib/cassandra/saved_caches
#elassandra_data_file_directories:
#- /var/lib/cassandra/data

#elassandra_phi_convict_threshold: 10                    # default = 8
#elassandra_commitlog_segment_size_in_mb: 64             # default 32
#elassandra_concurrent_compactors: 4                     # default 2
#elassandra_compaction_throughput_mb_per_sec: 250        # default 16
#elassandra_batch_size_warn_threshold_in_kb: 64          # default 5
#elassandra_batch_size_fail_threshold_in_kb: 640         # default 50
#elassandra_memtable_allocation_type: offheap_objects    # default = heap_buffers
#elassandra_memtable_flush_writers: 4                    # default = 2
#elassandra_concurrent_reads: 128                        # default = 32
#elassandra_concurrent_writes: 128                       # default = 32

# Set these variables if you want to custom the heap usage in the JVM
elassandra_max_heap_size: ~
elassandra_heap_newsize: ~

# certificates managment
elassandra_ssl: false
elassandra_keystore_password: changeit
